### ISSUE TITLE
inference issue

### ISSUE THREAD

**Issue by skunkwerk** [megvii-research/megactor#10]
Hi,

I'm having an issue running inference.  Any ideas why this would happen?

File "/run/megactor/eval.py", line 142, in eval
pixel_values_pose = crop_move_face(control, all_face_rects, target_size=size)
File "/run/megactor/animate/utils/util.py", line 418, in crop_move_face
for j, ids in enumerate(faces['image_ids']):
TypeError: list indices must be integers or slices, not str

https://github.com/megvii-research/megactor/blob/main/animate/utils/util.py#L418

thanks!

**Comment by EvePhil** [comment]
We uploaded a wrong eval.py that needed some fixing, already resolved. Thx for the report!
