### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by XiaoZong0** [megvii-research/megactor#14]
在服务器上安装的时候报下面的错误，有没有人分析一下可能是什么原因？
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tiqmryer/deepspeed_b5c74bcf93264dae8197d11c45274a64/setup.py", line 100, in <module>
          cuda_major_ver, cuda_minor_ver = installed_cuda_version()
        File "/tmp/pip-install-tiqmryer/deepspeed_b5c74bcf93264dae8197d11c45274a64/op_builder/builder.py", line 47, in installed_cuda_version
          import torch.utils.cpp_extension
        File "/dfs/data/miniconda/envs/megactor/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 25, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/dfs/data/miniconda/envs/megactor/lib/python3.10/site-packages/pkg_resources/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed

**Comment by XiaoZong0** [comment]
好像是因为deepspeed这个包安装失败的原因，尝试了很多办法，目前还没安装成功

**Comment by lhd777** [comment]
Deepspeed 是一个在训练时候使用的第三方包，如果只是使用Megactor的推理功能，可以不安装Deepspeed

**Comment by XiaoZong0** [comment]
也就是说在配置环境的时候，可以把environment.yaml里面的deepspeed删掉是吗？

---- 回复的原邮件 ----
| 发件人 | Huadong ***@***.***> |
| 发送日期 | 2024年06月28日 10:48 |
| 收件人 | megvii-research/megactor ***@***.***> |
| 抄送人 | Zoe ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [megvii-research/megactor] 安装失败 (Issue #14) |

Deepspeed 是一个在训练时候使用的第三方包，如果只是使用Megactor的推理功能，可以不安装Deepspeed
