### ISSUE TITLE
./weights/aux/densepose_model.pkl not found!

### ISSUE THREAD

**Issue by D-Mad** [megvii-research/megactor#7]
I can't find the models here

![image](https://github.com/megvii-research/megactor/assets/8207507/33120c8b-642f-41f1-baf0-7990b56d705e)

**Comment by EvePhil** [comment]
Hi, we uploaded our pretrained weights together with other incooporated models here, so you may simply do 
```
git clone https://huggingface.co/HVSiniX/RawVideoDriven && ln -s RawVideoDriven/weights weights
```
hopefully that would come helpful
